

export enum RunnerEventTypeEnum {
    CONFIGURATION_EVENT,
    TEST_SUITE_START_EVENT,
    TEST_SUITE_END_EVENT,
    FEATURE_START_EVENT,
    FEATURE_END_EVENT,
    HOOKS_START_EVENT,
    HOOKS_END_EVENT,
    TEST_START_EVENT,
    TEST_END_EVENT,
    PARAMETRIZED_TEST_START_EVENT,
    PARAMETRIZED_TEST_END_EVENT,
    SCENARIO_START_EVENT,
    SCENARIO_END_EVENT,
    STEP_START_EVENT,
    STEP_END_EVENT,
    LOG_EVENT,
    ERROR_EVENT,
    RUNNER_STOPPED_EVENT,
}
