
server:
    port: 7788
    shutdown: graceful
    servlet:
        context-path: "${contextPath:/}"

logging:
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger [%mdc{}] - %msg%n"
    level:
        root: WARN
        org.springframework.web: DEBUG
        com.testerum: DEBUG

management:
    endpoints:
        web:
            base-path: /management
            exposure:
              include: info, health

spring:
    resources:
        static-locations: "classpath:/frontend"
    banner:
        location: testerum-report-server-banner.txt
