/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.testerum.java-conventions")
}

dependencies {
    implementation(project(":testerum-runner-api"))
    implementation("com.testerum:testerum-steps-api:develop-SNAPSHOT")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.4.10")
    implementation("org.slf4j:slf4j-api:1.7.25")
    implementation("org.springframework:spring-core:5.2.8.RELEASE")
    implementation("org.springframework:spring-beans:5.2.8.RELEASE")
    implementation("org.springframework:spring-context:5.2.8.RELEASE")
    implementation("org.springframework:spring-context-support:5.2.8.RELEASE")
    runtimeOnly("org.slf4j:jcl-over-slf4j:1.7.25")
}

description = "testerum-runner-spring"
