/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.testerum.java-conventions")
}

dependencies {
    implementation(project(":testerum-runner-cmdline"))
    implementation(project(":assertion-steps"))
    implementation(project(":debug-steps"))
    implementation(project(":http-steps"))
    implementation(project(":json-steps"))
    implementation(project(":rdbms-steps"))
    implementation(project(":selenium-steps"))
    implementation(project(":util-steps"))
    implementation(project(":vars-steps"))
}

description = "testerum-runner-cmdline-debug"
