/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.testerum.java-conventions")
}

dependencies {
    implementation(project(":common-jdk"))
    implementation(project(":common-kotlin"))
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.4.10")
    implementation("org.apache.commons:commons-lang3:3.8.1")
    implementation("org.zeroturnaround:zt-exec:1.10")
    implementation("org.zeroturnaround:zt-process-killer:1.8")
    implementation("com.jgoodies:jgoodies-forms:1.9.0")
    implementation("com.jgoodies:looks:2.2.2")
}

description = "web-launcher"
